import { DEFAULT_SCENE_PROMPT, buildFallbackPoseOptions } from '../data/poseLibrary';

const GEMINI_MODEL = 'gemini-2.5-flash';
const GEMINI_ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

function stripCodeFences(text) {
  return text.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```$/i, '').trim();
}

function normalizePayload(payload, prompt, mode) {
  const fallback = buildFallbackPoseOptions(prompt, mode);

  if (!payload || typeof payload !== 'object') {
    return fallback;
  }

  const poses = Array.isArray(payload.poses) && payload.poses.length > 0 ? payload.poses : fallback.poses;

  return {
    sceneLabel: payload.sceneLabel || fallback.sceneLabel,
    mood: payload.mood || fallback.mood,
    summary: payload.summary || fallback.summary,
    source: payload.source || 'gemini',
    poses: poses.map((pose, index) => ({
      id: pose.id || `gemini-pose-${index + 1}`,
      title: pose.title || `Pose ${index + 1}`,
      subtitle: pose.subtitle || 'Generated by Gemini for this scene.',
      alignmentCue: pose.alignmentCue || 'Keep the body readable and the outline clean.',
      rationale: pose.rationale || 'Scene-aware suggestion from Gemini.',
      score: typeof pose.score === 'number' ? pose.score : 90 - index,
      people: Array.isArray(pose.people) && pose.people.length > 0 ? pose.people : fallback.poses[index % fallback.poses.length].people,
    })),
  };
}

async function queryGemini(prompt, mode, apiKey) {
  const response = await fetch(`${GEMINI_ENDPOINT}?key=${apiKey}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: `You are CamAI. Analyze the scene and generate 3-4 pose options for a ${mode} photo shoot.
Return valid JSON only with this structure:\n{
  "sceneLabel": string,
  "mood": string,
  "summary": string,
  "source": "gemini",
  "poses": [
    {
      "id": string,
      "title": string,
      "subtitle": string,
      "alignmentCue": string,
      "rationale": string,
      "score": number,
      "people": [
        {
          "joints": {
            "head": {"x": number, "y": number},
            "neck": {"x": number, "y": number},
            "leftShoulder": {"x": number, "y": number},
            "rightShoulder": {"x": number, "y": number},
            "leftElbow": {"x": number, "y": number},
            "rightElbow": {"x": number, "y": number},
            "leftHand": {"x": number, "y": number},
            "rightHand": {"x": number, "y": number},
            "torso": {"x": number, "y": number},
            "leftHip": {"x": number, "y": number},
            "rightHip": {"x": number, "y": number},
            "leftKnee": {"x": number, "y": number},
            "rightKnee": {"x": number, "y": number},
            "leftFoot": {"x": number, "y": number},
            "rightFoot": {"x": number, "y": number}
          }
        }
      ]
    }
  ]
}\n\nScene prompt: ${prompt}`,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.7,
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Gemini request failed: ${response.status}`);
  }

  const json = await response.json();
  const text = json?.candidates?.[0]?.content?.parts?.map(part => part.text ?? '').join('') ?? '';
  const normalizedText = stripCodeFences(text);

  if (!normalizedText) {
    throw new Error('Gemini returned an empty payload.');
  }

  return normalizePayload(JSON.parse(normalizedText), prompt, mode);
}

export async function analyzeSceneAndGeneratePoses({
  prompt = DEFAULT_SCENE_PROMPT,
  mode = 'solo',
  apiKey,
}) {
  const fallback = buildFallbackPoseOptions(prompt, mode);

  if (!apiKey) {
    return fallback;
  }

  try {
    return await queryGemini(prompt, mode, apiKey);
  } catch (error) {
    return fallback;
  }
}
